// <auto-generated />
using System;
using BackendExam.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendExam.Migrations
{
    [DbContext(typeof(BackendExamDbContext))]
    partial class BackendExamDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendExam.Models.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("name")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("BackendExam.Models.Ticket_Comments", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Ticketsid")
                        .HasColumnType("int");

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("ticket_id")
                        .HasColumnType("int");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Ticketsid");

                    b.HasIndex("Usersid");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("BackendExam.Models.Ticket_status_logs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Ticketsid")
                        .HasColumnType("int");

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.Property<DateTime>("changed_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("changed_by")
                        .HasColumnType("int");

                    b.Property<int>("new_status")
                        .HasColumnType("int");

                    b.Property<int>("old_status")
                        .HasColumnType("int");

                    b.Property<int>("ticket_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Ticketsid");

                    b.HasIndex("Usersid");

                    b.ToTable("ticket_Status_Logs");
                });

            modelBuilder.Entity("BackendExam.Models.Tickets", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Usersid")
                        .HasColumnType("int");

                    b.Property<int?>("assigned_to")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<int>("created_by")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("Usersid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("BackendExam.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Rolesid")
                        .HasColumnType("int");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("role_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Rolesid");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BackendExam.Models.Ticket_Comments", b =>
                {
                    b.HasOne("BackendExam.Models.Tickets", "Tickets")
                        .WithMany("Ticket_Comments")
                        .HasForeignKey("Ticketsid");

                    b.HasOne("BackendExam.Models.Users", "Users")
                        .WithMany("Ticket_Comments")
                        .HasForeignKey("Usersid");

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackendExam.Models.Ticket_status_logs", b =>
                {
                    b.HasOne("BackendExam.Models.Tickets", "Tickets")
                        .WithMany("Ticket_Status_Logs")
                        .HasForeignKey("Ticketsid");

                    b.HasOne("BackendExam.Models.Users", "Users")
                        .WithMany("Ticket_Status_Logs")
                        .HasForeignKey("Usersid");

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackendExam.Models.Tickets", b =>
                {
                    b.HasOne("BackendExam.Models.Users", "Users")
                        .WithMany("Tickets")
                        .HasForeignKey("Usersid");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackendExam.Models.Users", b =>
                {
                    b.HasOne("BackendExam.Models.Roles", "Roles")
                        .WithMany("Users")
                        .HasForeignKey("Rolesid");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("BackendExam.Models.Roles", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BackendExam.Models.Tickets", b =>
                {
                    b.Navigation("Ticket_Comments");

                    b.Navigation("Ticket_Status_Logs");
                });

            modelBuilder.Entity("BackendExam.Models.Users", b =>
                {
                    b.Navigation("Ticket_Comments");

                    b.Navigation("Ticket_Status_Logs");

                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
